import json
import os

from ..model.item import EwCosmeticItem

unique_smeltables = ['skinsuit', 'eldritchsoul', 'safaribadge', 'cloutgoggles', 'programmersocks', 'maidoutfit', 'drapeddress', 'widebrimmedhat', 'cigaretteholder']

# Because all profollean cosmetics are complicated, they are in the same boat as unique_smeltables. DO NOT add profollean cosmetics to unique_smeltables! 
# Profollean cosmetics and unique_smeltables are not smeltable in the slimepoudrin + stylecosmeticitem recipe. (Example: 4 slimepoudrin + 1 coolbeans will NOT give you a programmer socks or a cool profollean cosmetic! ) 
cosmetic_items_list = [
    EwCosmeticItem(
        id_cosmetic = "propellerhat",
        str_name = "propeller hat",
        str_desc = "A simple multi-color striped hat with a propeller on top. A staple of every juvenile's youth.",
        str_onbreak = "Your hat takes a hit, detatching the propeller and sending it twirling into the stratosphere. Looks like you'll never see it again.",
        rarity = "Plebeian",
        durability = 2500000,
        size = 1,
        style = "cute",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "mininghelmet",
        str_name = "mining helmet",
        str_desc = "A typical construction hard hat with a head lamp strapped onto it.",
        rarity = "Plebeian",
        ability = "lucky",
        durability = 5000000,
        size = 2,
        style = "tough",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pickelhaube",
        str_name = "pickelhaube",
        str_desc = "A traditional Prussian spiked helmet from the nineteenth century.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "fedora",
        str_name = "fedora",
        str_desc = "A soft brimmed hat with a pinched crown. A classic piece of vintage Americana and a staple of film noir. Not to be confused with the trilby, the fedora is a hat befitting the hardboiled men of its time.",
        rarity = "Plebeian",
        durability = 1250000.0,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "baseballcap",
        str_name = "baseball cap",
        str_desc = "A classic baseball cap. A staple of American culture and subsequently freedom from tyranny. If you don't own at least one of these hats you might as well have hopped the fence from Tijuana last night. Yeah, I'm racist, that going to be a problem for you??",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "backwardsbaseballcap",
        str_name = "backwards baseball cap",
        str_desc = "A classic baseball cap' with an urban twist! Heh, 'sup dawg? Nothing much, man. You know me, just mining some goddamn slime. Word 'n shit. Hell yeah.",
        str_onadorn = "You whip out your baseball cap and apply it...backwards. Fuck, now we're getting serious.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "piratehat",
        str_name = "pirate hat",
        str_desc = "A swashbuckling buccaneer's tricorne, stylized with a jolly roger on the front.",
        str_onadorn = "Y'ARRRRRRR! You adorn ye' tricorne and spit at a nearby pedestrian.",
        str_onbreak = "You hat is torn to shreds. Welp, no more shivering timbers.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "eyepatch",
        str_name = "eyepatch",
        str_desc = "A black eyepatch. A striking accessory for the particularly swashbuckling, chauvinistic, or generally hardboiled of you. Genuine lack of two eyes optional and not recommended.",
        str_unadorn = "You remove your eyepatch to reveal the grisly wound benea- wait. Your eye is just fine! What kind of pathetic pirate LARPer did you turn out to be?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cigarette",
        str_name = "cigarette",
        str_desc = "A single cigarette sticking out of your mouth. You huff these things down in seconds but you're never seen without one. Everyone thinks you're really, really cool.",
        str_onadorn = "You stick the cigarette in your mouth, suave as a baby's bottom. You wonder how many of these could fit in your mouth.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "headband",
        str_name = "headband",
        str_desc = "A headband wrapped tightly around your forehead with long, flowing ends.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "handkerchief",
        str_name = "handkerchief",
        str_desc = "A bandanna tied on your head, creating a simple cap.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "bandanna",
        str_name = "bandanna",
        str_desc = "A handkerchief tied around your neck and covering your lower face.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofsunglasses",
        str_name = "pair of sunglasses",
        str_desc = "An iconic pair of black sunglasses. Widely recognized as the coolest thing you can wear.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofglasses",
        str_name = "pair of glasses",
        str_desc = "A simple pair of eyeglasses. You have perfectly serviceable eyesight, but you are a sucker for the bookworm aesthetic. People with actual issues with sight hate you.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "birthdayhat",
        str_name = "birthday hat",
        str_desc = "A striped, multi-color birthday hat. ",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "scarf",
        str_name = "scarf",
        str_desc = "A very thick striped wool scarf, in case 110' degrees is too nippy for you.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "witchhat",
        str_name = "witch hat",
        str_desc = "A pointy, cone-shaped hat with a wide brim. It exudes a spooky essence.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bomberhat",
        str_name = "bomber hat",
        str_desc = "A thick fur and leather aviator's hat.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "tuxedo",
        str_name = "tuxedo",
        str_desc = "A classy, semi-formal suit for dashing rogues you can't help but love. Instant charisma granted upon each !adorn.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "beanie",
        str_name = "beanie",
        str_desc = "A simple beanie with a pointed top and a slip stitch brim.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic="eldritchsoul",
        str_name="eldritch soul",
        str_desc="The inside of this bottle is pitch black, and occasionally you see an insect-like appendage rap against the glass. If you listen to it closely you can hear it whispering tesseracts and imaginary numbers.",
        rarity="Patrician",
        durability=2500000,
        style="cool",
        acquisition="eldritchsoul",
        price=50000,
        vendors=[],
    ),
    EwCosmeticItem(
        id_cosmetic = "jestershat",
        str_name = "jester's hat",
        str_desc = "A ridiculous, multi-colored hat with four bells dangling from protruding sleeves.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairof3dglasses",
        str_name = "pair of 3D glasses",
        str_desc = "A pair of totally tubular, ridiculously radical 3D glasses. Straight up stereoscopic, dude!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "necktie",
        str_name = "necktie",
        str_desc = "A vintage necktie, reeking of coffee, college, and shaving cream.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "vikinghelmet",
        str_name = "viking helmet",
        str_desc = "A pointy bronze helmet with two sharp horns jutting out of the base.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofflipflops",
        str_name = "pair of flip flops",
        str_desc = "A pair of loud, obnoxious flip flops. The price of your comfort is higher than you could ever know.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "fez",
        str_name = "fez",
        str_desc = "A short fez with a tassel attached to the top. Fezzes are cool. Or, are bowties cool? You forget, and frankly you're embarrassed you remember either one of them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bowtie",
        str_name = "bowtie",
        str_desc = "A quite dapper, neatly tied butterfly bowtie. Bowties are cool. Or, are fezzes cool? You forget, and frankly you're embarrassed you remember either one of them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cowboyhat",
        str_name = "cowboy hat",
        str_desc = "An essential piece of Wild West memorabilia, a bonafide ten gallon Stetson. Befitting the individualistic individuals that made them famous. Yeehaw, and all that stuff.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "kepi",
        str_name = "kepi",
        str_desc = "A short kepi with a sunken top and an insignia on the front.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "tamoshanter",
        str_name = "tam o' shanter",
        str_desc = "A traditional Scottish wool bonnet with a plaid pattern.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "ushanka",
        str_name = "ushanka",
        str_desc = "A traditional Russian fur cap with thick wool ear flaps.",
        rarity = "Plebeian",
        durability = 5000000,
        size = 2,
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "karategi",
        str_name = "karategi",
        str_desc = "A traditional Japanese karateka's outfiit, complete with a belt with extended ends that easily flow in the wind for dramatic effect.",
        rarity = "Plebeian",
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "turban",
        str_name = "turban",
        str_desc = "A traditional Arabian headdress, lavishly decorated with a single large jewel and protruding peacock feather.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "nemes",
        str_name = "nemes",
        str_desc = "The traditional ancient Egyptian pharaoh's striped head cloth.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "varsityjacket",
        str_name = "varsity jacket",
        str_desc = "An American baseball jacket, with a large insignia on the left side of the chest.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "sombrero",
        str_name = "sombrero",
        str_desc = "A traditional Mexican sombrero, with an extra-wide brim to protect you from the blistering Arizonian sun.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "hawaiianshirt",
        str_name = "hawaiian shirt",
        str_desc = "A brightly colored Hawaiian shirt with a floral pattern. It reeks of slima colada and the complementary shampoo from the resort in Assault Flats Beach.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "fursuit",
        str_name = "fursuit",
        str_desc = "A fursuit. Custom-made and complete with high quality faux fur, padded digitigrade legs, follow-me eyes, adjustable facial expressions, and a fan in the head. It is modeled off your original character, also known as your fursona. Some would call its character design 'ugly' or 'embarrassing,' but you think it's perfect.",
        rarity = "Patrician",
        durability = 10000000,
        size = 2,
        style = "cute",
        freshness = 11,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "diadem",
        str_name = "diadem",
        str_desc = "The traditional Greco-Roman laurel wreath symbolizing sovereignty and power. Be careful about wearing this around in public, you might just wake up with 23 stab wounds.",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "billshat",
        str_name = "Bill's Hat",
        str_desc = "A military beret with a shield insignia on the front.",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "weddingring",
        str_name = "wedding ring",
        str_desc = "A silver ring with a decently large diamond on top. For the person you love most in the entire world. <3",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "earbuds",
        str_name = "earbuds",
        str_desc = "A pair of white standard iPod earbuds. Who knows what sort of tasty jams you must be listening to while walking down the street?",
        rarity = "Patrician",
        durability = 10000000,
        style = "smart",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "nursesoutfit",
        str_name = "nurse's outfit",
        str_desc = "A disturbingly revealing nurse's outfit that shows off your lumpy, fleshy visage. No one likes that you wear this. Theming bonus for responding to people's crackpot ideas in the nurse's office, though.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "heartboxers",
        str_name = "heart boxers",
        str_desc = "A staple of comedy. A pair of white boxers with stylized cartoon hearts tiled all over it. Sure hope your pants aren't hilariously ripped or unadorned while you're wearing these, how embarrassing! Hahaha! We like to have fun here.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "kilt",
        str_name = "Kilt",
        str_desc = "A traditional scottish garmet that's plaid, and it's not a fuckin' skirt, aight?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cigar",
        str_name = "Cigar",
        str_desc = "Much more manly then a puny cigarette. This cigar has been freshly imported from cuba and is thick enough to last for hours.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "captainshat",
        str_name = "Captain's Hat",
        str_desc = "The perfect hat for sailing across the Slime Sea, commanding a navy fleet, or prematurely ending your lucrative My Little Pony review series in favor of starting a shitty Pokemon Nuzlocke series. For shame.",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "juveolantern",
        str_name = "Juve-O'-Lantern",
        str_desc = "Hand-carved with a hole just barely big enough to fit your head in, this Juve O' Lantern severely hinders your combat ability. But, you look fucking sick while wearing it, so who cares.",
        durability = 2500000,
        style = "cute",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bowlerhat",
        str_name = "Bowler Hat",
        str_desc = "A simply traditional billyock. You're gonna be the talk of the toy box with this dashing felt cosmetic! Now you just have to work on the moustache.",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "cabbagetreehat",
        str_name = "Cabbage Tree Hat",
        str_desc = "An unmistakably Australian hat, with a wide brim and a high crown.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "braces",
        str_name = "Braces",
        str_desc = "An old fashioned orthodontic headgear. Elaborate metal wires and braces hold your nearly eroded, crooked teeth together in what can genously be called a mouth. You are in agony, and so is everyone that looks at you.",
        durability = 3750000.0,
        style = "smart",
        freshness = 1,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "hoodie",
        str_name = "Hoodie",
        str_desc = "Perfect for keeping warm in the middle of the blisteringly hot Arizonian desert! Heatstroke or bust!",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "copbadge",
        str_name = "Cop Badge",
        str_desc = "What the fuck are you doing with this thing? Are you TRYING to make the sewers your permanent residence? Acquaint yourself with the !drop command and FAST, before you don't have a body to wear the badge on.",
        durability = 2500000,
        style = "smart",
        freshness = 2,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "strawhat",
        str_name = "Straw Hat",
        str_desc = "A wide-brimmed straw hat, the perfect hat for farming.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "cosplayhorns",
        str_name = "Cosplay Horns",
        str_desc = "You're not entirely sure what these things are, but they sort of look like brightly painted, candy corn colored, paper mache horns that are hot glued onto a black headband. Their purpose is mysterious, but for some reason you are inclined to adorn them' perhaps you understood their importance in a past life.",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "yourfavoritehat",
        str_name = "***Your Favorite Hat***",
        str_desc = "***It fits perfectly, and it's just your style! You love wearing this cosmetic far more than any other, it's simply the best.***",
        durability = 2500000,
        style = "cute",
        freshness = 10,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pajamaonesie",
        str_name = "Pajama Onesie",
        str_desc = "A soft jumpsuit with an audacious, repeating design printed over the entire cosmetic. You feel like getting a little bit fucking rowdy wearing this outrageous onesie. ",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofcircularsunglasses",
        str_name = "Pair of Circular Sunglasses",
        str_desc = "Sunglasses, but in a circle! Genius! You can't wait to show the world your hot takes on television shows for girls.",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "flowercrown",
        str_name = "Flower Crown",
        str_desc = "A lovingly handcrafted crown of flowers, connected by a string. You're gonna be famous on Pinterest with a look like this!",
        durability = 2500000,
        style = "cute",
        freshness = 7,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "spikedbracelets",
        str_name = "Spiked Bracelets",
        str_desc = "Hilariously unrealistic spiked bracelets, ala Bowser, King of the Koopas. You're hyper aware of these fashion disasters whenever you're walking, making sure to swing them as far away from your body as possible.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "slimecorppin",
        str_name = "SlimeCorp Pin",
        str_desc = "An enamel pin of the SlimeCorp logo, a badge of loyalty to your favorite charismatic megacorporation. Dude, like, *'Follow He Who Turns The Wheels'*, bro!!",
        durability = 2500000,
        style = "smart",
        freshness = 10,
        acquisition = "smelting",
        vendors = ['The Breakroom'],
    ),
    EwCosmeticItem(
        id_cosmetic = "overalls",
        str_name = "Overalls",
        str_desc = "Simple, humble denim overalls, for a simple, humble farmer such as yourself.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "rustynail",
        str_name = "Rusty Nail",
        str_desc = "A large, rusty nail, planted right between the sides of your head, like some kind of frankenstein costume piece. This one's the real deal though... oh god the pain...",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "fullmetaljacket",
        str_name = "Full Metal Jacket",
        str_desc = "A black leather jacket affixed with more spikes than you can count on your fingers and toes. Be careful not to bump into anyone with this thing on.",
        durability = 5000000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "tinfoilhat",
        str_name = "Tinfoil Hat",
        str_desc = "A hat that protects you from SlimeCorp's patent-pending 5G binaural brain waves, or so the folks on the internet have told you.",
        durability = 5000000,
        style = "smart",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "resplendentcoronet",
        str_name = "Resplendent Coronet",
        str_desc = "A crown worn by only the most elegant and regal of nobles. When you put it on, you really feel like you fuckin' own the place.",
        durability = 5000000,
        style = "beautiful",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "partyhat",
        str_name = "Party Hat",
        str_desc = "A colorful party hat, shimmering from the copious amounts of glitter applied to it. Just wearing makes you feel like causing a public disturbance of a party.",
        durability = 5000000,
        style = "beautiful",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "raincoat",
        str_name = "Raincoat",
        str_desc = "A specially engineered piece of personal armor, that protects you from the deadly threat from above.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "halloweenmedallion",
        str_name = "Double Halloween Medallion",
        str_desc = "A glistening crystal medallion, carved in the shape of a pumpkin. It is strewn together with black pearls. Awarded only to the bravest of souls who managed to best the Double Headless Double Horseman in combat.",
        rarity = "Double Halloween",
        style = "cool",
        ingredients = "HorsemanSoul",
        acquisition = "DH-bossfight",
    ),
    EwCosmeticItem(
        id_cosmetic = "pileus",
        str_name = "Pileus",
        str_desc = "A symbol of freedom and liberty. In ancient times, these felt caps were given to slaves who had been emancipated.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        price = 100,
    ),
    EwCosmeticItem(
        id_cosmetic = "seacowcostume",
        str_name = "Attractive Gray Sea Cow Mascot Costume for Adult",
        str_desc = "Attractive. That's really all there is to say on the matter.",
        rarity = "Patrician",
        durability = 2500000,
        style = "beautiful",
        ability = "furry",
        freshness = 2,
        price = 100000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "wrappingpaperhat",
        str_name = "Wrapping Paper Hat",
        str_desc = "A hat made out of wrapping paper, fashioned in a way rather similar to a newspaper hat. How festive!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        price = 1000,
        vendors = ['Glocksbury Comics'],
    ),
    EwCosmeticItem(
        id_cosmetic = "knightarmor",
        str_name = "Steel knight armor",
        str_desc = "A shining set of steel armor.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "velcroshoes",
        str_name = "Velcro Shoes",
        str_desc = "Juveniles in the city always had a hard time tying their laces, so these stylish kicks are perfect for them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        price = 1000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "crocs",
        str_name = "Crocs",
        str_desc = "The perfect pair of footwear for when you want spotted dots of sunburn on your feet, unless you're wearing socks that is. If that's the case ignore that earlier statement.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        price = 1000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "janusmask",
        str_name = "Janus Mask",
        str_desc = "A simple, yet elegant mask, awarded to those deemed worthy by Janus himself at the end of every Swilldermuk. It's enigmatic powers allow you to procure prank items from thin air.",
        rarity = "Swilldermuk",
        durability = 10000000,
        style = "cool",
        ingredients = "SwilldermukFinalGambit",
        acquisition = "SwilldermukEnd",
    ),
    EwCosmeticItem(
        id_cosmetic = "leatherjacket",
        str_name = "Leather Jacket",
        str_desc = "A black leather jacket. Gangs of Killers stalking the streets are often found wearing these.",
        rarity = "Patrician",
        durability = 2500000,
        style = "cool",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "afrowig",
        str_name = "Afro Wig",
        str_desc = "The perfect hair-do for a 70's party or a pool party just be sure to keep a can of hairspray and comb at hand.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pompadourwig",
        str_name = "Pompadour Wig",
        str_desc = "A must have for any wannabe greaser or school delinquent in general. Make sure to wear it like a true king.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "powderedwig",
        str_name = "Powdered Wig",
        str_desc = "If it was good enough for the british and founding fathers, it's good enough for us, right? Just make sure you don't share this wig without cleaning it.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "rainbowafrowig",
        str_name = "Rainbow Afro Wig",
        str_desc = "A colorful wig worthy of a real chuckle.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "ghostlygibus",
        str_name = "Ghostly Gibus",
        str_desc = "A crooked old top hat with a spooky toy ghost popping out of the top.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "gasmask",
        str_name = "Gas Mask",
        str_desc = "A dysfunctional cold war era gas mask that fully encapsulates the head.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "firefightershelmet",
        str_name = "Firefighter's Helmet",
        str_desc = "A old NLACakaNM wide-brimmed red firefighter's helmet. No one knows what happened to the firefighters of Endless War.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofpoindexterglasses",
        str_name = "Pair Of Poindexter Glasses",
        str_desc = "A pair of thick rim glasses taped together at the middle. Worthy of any true nerd or nerdette.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "duncecap",
        str_name = "Dunce Cap",
        str_desc = "It's a pointy cap that says dunce on it, duh! You're a real smartie aren't you?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 2,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "vrheadset",
        str_name = "VR Headset",
        str_desc = "Endless War -- now in stunning VR!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "blindfold",
        str_name = "Blindfold",
        str_desc = "Ok now you're just bragging. Walking around with a blindfold of all things? How ridiculous!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "chickenmask",
        str_name = "Chicken Mask",
        str_desc = "The rubber chicken mask gives you a strange vibe. It stinks of sweat and dried blood.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "mountiehat",
        str_name = "Mountie Hat",
        str_desc = "A hat that's mostly used by Canada's royal mounted police, but how did it get here? Did it float down the slime river?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bearskinhat",
        str_name = "Bearskin Hat",
        str_desc = "A towering fuzzy hat that's commonly worn by guards of the british royal guard.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "aviatorshat",
        str_name = "Aviator's Hat",
        str_desc = "A leather hat with a neat pair of goggles on it. Perfect for an unfortunate circumnavigation of the world.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 6,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "militaryberet",
        str_name = "Military Beret",
        str_desc = "A good soldier needs good headwear, and that's where this beret comes in.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "felinehat",
        str_name = "Feline Hat",
        str_desc = "A hat striped with red and white is quite right for a fanciful fight! It's a funny hat at that, and it looks like it's been worn by a cat!",
        rarity = "Plebeian",
        durability = 100,
        style = "cute",
        freshness = 1,
        acquisition = "smelting",
        price = 100,
        vendors = ['Secret Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "tikihead",
        str_name = "Tiki Head",
        str_desc = "A wearable tiki head worthy of any luau or tropical island themed party.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "reinforcedkfcbucket",
        str_name = "Reinforced KFC Bucket",
        str_desc = "A stronger, more durable version of the average KFC bucket. Intended to be worn by shamblers in Dr. Downpour's legion of the undead.",
        rarity = "Patrician",
        durability = 5000000,
        style = "smart",
        price = 1000,
        vendors = ['Downpour Armament Vending Machines'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "reinforcedjuveolantern",
        str_name = "Reinforced Juve-O'-Lantern",
        str_desc = "A stronger, more durable version of the average Juve-O'-Lantern. Intended to be worn by shamblers in Dr. Downpour's legion of the undead.",
        rarity = "Patrician",
        durability = 5000000,
        style = "cute",
        price = 2000,
        vendors = ['Downpour Armament Vending Machines'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "rollerblades",
        str_name = "Rollerblades",
        str_desc = "A wicked sicknasty D-I-Y set of inline skates. These ones may not be magnetically driven or powered by netrium batteries, but they do the job just fine.",
        str_onadorn = "You slip into your rollerblades and tighten the straps. Let's get scratchin'.",
        str_unadorn = "You unfasten the belts and straps on your rollerblades.",
        str_onbreak = "Your rollerblades break down! Time to make a break for it on foot!",
        rarity = "Patrician",
        ability = "boost",
        durability = 250000,
        style = "cool",
        freshness = 10,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "garfieldtail",
        str_name = "Garfield's Tail",
        str_desc = "The tail of a large ginger cat, \"borrowed\" from it's owner.",
        str_onadorn = "You adorn Garfield's Tail, and feel an overwhelming hatred for Mondays creep into your mind...",
        str_unadorn = "You remove Garfield's Tail. Maybe Mondays aren't so bad after all...",
        str_onbreak = "Whaaaa-? Garfield's Tail disintegrates.",
        rarity = "Safari",
        ability = "mondayblues",
        durability = 250000,
        style = "cute",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "normalplume",
        str_name = "Normal Plume",
        str_desc = "A Normal Plume plucked from N400. Dogs hate this thing.",
        str_onadorn = "You adorn the Normal Plume! Normcoin is too big to fail, I tell you!",
        str_unadorn = "You remove the Normal Plume. Thank god, you almost invested all your savings into a proprietary soul-based cryptocurrency!",
        str_onbreak = "Whaaaa-? The Normal Plume disintegrates.",
        rarity = "Safari",
        ability = "norm",
        durability = 250000,
        style = "beautiful",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic="chastitybelt",
        str_name="Chastity Belt",
        str_desc="A metal codpiece used to protect against sexual urges and, when necessary, pickpockets. It's locked and there's no key to go with it.",
        str_onadorn="You strap on the chastity belt, locking it up tight. Maybe too tight, you have no means of pissing now.",
        str_unadorn="You rip off your legs, tear the belt off, then try reattaching your legs. Wait, that worked?",
        str_onbreak="",
        rarity="Plebeian",
        durability=250000,
        style="beautiful",
        freshness=10,
        acquisition="",
        price=200000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic="skinsuit",
        str_name="Alien Skin Suit",
        str_desc="A patched together suit made out of the scalps of various extraterrestrials. You're shocked this fools anyone, but they seem to work.",
        str_onadorn="You cloak up into the alien skinsuit. Who's invading now, body snatchers?",
        str_unadorn="You take off the skinsuit. Phew, it was hot and weirdly gelatinous in there.",
        str_onbreak="",
        rarity="Plebeian",
        durability=250000,
        style="smart",
        freshness=10,
        acquisition='smelting',
        price=200000,
        vendors=[],
    ),
    EwCosmeticItem(
        id_cosmetic="alienscalp",
        str_name="Alien Scalp",
        str_desc="It's the severed scalp of one of NLACakaNM's many alien races. Most of them don't have hair though, so you guess it's more of like a head skin...chunk.",
        str_onadorn="You attach the scalp to your belt. Another freak exterminated.",
        str_unadorn="You put away the alien scalp. Don't want your space friends to see this...",
        str_onbreak="",
        rarity="Plebeian",
        durability=250000,
        style="tough",
        freshness=10,
        price=200000,
    ),
    EwCosmeticItem(
        id_cosmetic = "guillotinecharm",
        str_name = "Guillotine Charm",
        str_desc = "A miniature guillotine strung on a piece of rope to go around your neck. What could go wrong?",
        str_onadorn = "You adorn the Guillotine Charm. You feel an intense need to abolish the monarchy.",
        str_unadorn = "You remove the Guillotine Charm. Hmmmm, maybe we SHOULD have a monarchy...",
        str_onbreak = "Whaaaa-? The Guillotine Charm disintegrates.",
        rarity = "Safari",
        ability = "executioner",
        durability = 250000,
        style = "tough",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "ominousslippers",
        str_name = "Ominous Slippers",
        str_desc = "Ominous Slippers fashioned from the paws of an incredibly large dog. One step closer to a full fursuit...",
        str_onadorn = "You adorn the Ominous Slippers. Comfortable, yet something within you wishes to be covered in MORE fur...",
        str_unadorn = "You remove the Ominous Slippers. Phew, you almost *liked* wearing that furry shit for a while there! haha...",
        str_onbreak = "Whaaaa-? The Ominous Slippers disintegrates.",
        rarity = "Safari",
        ability = "moonlighter",
        durability = 250000,
        style = "cute",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "navaluniform",
        str_name = "Naval Uniform",
        str_desc = "One of those old-fashioned Navy uniforms, the bane of children across the globe. It smells faintly of whale...",
        str_onadorn = "You adorn the Naval Uniform. You feel like a kid again! A *naval* kid!",
        str_unadorn = "You remove the Naval Uniform. The responsibilities and pains of adulthood creep back into you. Oh...",
        str_onbreak = "Whaaaa-? The Naval Uniform disintegrates.",
        rarity = "Safari",
        ability = "childatheart",
        durability = 250000,
        style = "smart",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "raccoonskincap",
        str_name = "Raccoon-skin Cap",
        str_desc = "A cap fashioned from the skin and fur of a raccoon. An iconic hunting cap, and favourite of rats everywhere.",
        str_onadorn = "You slap on the Raccoon-skin cap, the little tail at the back itching your neck.",
        str_unadorn = "You rip the Raccoon-skin cap off of your head at mach speed.",
        str_onbreak = "Whaaaa-? The Raccoon-skin cap runs off into the woods, sick of being a hat.",
        rarity = "Patrician",
        durability = 250000,
        style = "cool",
        freshness = 5,
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "safaribadge",
        str_name = "Safari Badge",
        str_desc = "A cardboard \"badge\" with \"Safari\" scrawled on it in crayon. It's even got double-sided tape instead of a safety pin! They didn't spare *any* expense!",
        str_onadorn = "You stick the Safari Badge to yourself. You feel a portion of your lost safari power return to you...",
        str_unadorn = "You unstick the Safari Badge from yourself. You feel drained of safari power.",
        str_onbreak = "Whaaaa-? The Safari Badge distintegrates before your very eyes. Thanks for the memories, little friend!",
        rarity = "Safari",
        ability = "safaripower",
        durability = 250000,
        style = "cool",
        freshness = 10,
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "dionaeashawl",
        str_name = "Dionaea Shawl",
        str_desc = "A fabric shawl, made from the dried corpse of Dionaea. Despite being fashioned from a corpse, it feels SO unbelievebly comfortable!",
        str_onadorn = "You wrap the Dionaea Shawl around your torso and start blushing. OMGz, it's, like so ganker-core!!! There's even a little head that sits on your shoulder!",
        str_unadorn = "You take off the Dionaea Shawl. Your vibe is thoroughly less Ganker-core than it was minutes ago.",
        str_onbreak = "Without warning, the Dionaea Shawl falls from your shoulders.",
        rarity = "Patrician",
        ability = "dionaea",
        durability = 250000,
        style = "cute",
        freshness = 10,
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "carrottopsmohawk",
        str_name = "Carrot Top's Mohawk",
        str_desc = "A sick-ass mohawk, both vegan **AND** cruelty-filled! It's positively scrumptious to nibble on.",
        str_onadorn = "You adorn Carrot Top's Mohawk, boosting your cool factor to **veggie-tastic**! You suddenly feel like... farming? How weird.",
        str_unadorn = "You remove Carrot Top's Mohawk, dropping your cool factor to **carrotphobic**! You suddenly feel like... killing juvies? How weird.",
        str_onbreak = "Whaaaa-? Carrot Top's Mohawk disintegrates on your head! You feel your cool factor plummeting to **famine-filled**.",
        rarity = "Patrician",
        durability = 250000,
        style = "cool",
        freshness = 10,
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "beekeepinghat",
        str_name = "Beekeeping Hat",
        str_desc = "A wide-brimmed hat with mesh veil, allowing absolutely 0 bees through. It's essential to anyone pursuing the NLACakaNM honey trade.",
        durability = 2500000,
        style = "smart",
        freshness = 7,
    ),
    EwCosmeticItem(
        id_cosmetic = "gardengankerpin",
        str_name = "Garden Ganker Pin",
        str_desc = "An enamel pin of the Garden Ganker logo, a badge of love towards your farming brethren. It's cheaply crafted, but it's the love that counts.",
        durability = 2500000,
        style = "tough",
        freshness = 3,
    ),
    EwCosmeticItem(
        id_cosmetic = "rosehairclip",
        str_name = "Rose Hairclip",
        str_desc = "A hairclip that looks and smells exactly like a rose. It's both subtle and gorgeous, perfect for your head!",
        durability = 2500000,
        style = "beautiful",
        freshness = 5,
    ),
    EwCosmeticItem(
        id_cosmetic = "cornearrings",
        str_name = "Corn Earrings",
        str_desc = "A pair of corn-shaped yellow and green jewel earrings, given to you by the Garden Gankers for getting far too many party points. They look absolutely fabulous on you, just gorgeous.",
        str_onadorn = "You adorn the Corn Earrings. They're **way** heavier than you imagined, but that's fine. Your ears can suffer.",
        str_unadorn = "You remove Corn Earrings, making you feel much less corntificated. Your ears are much happier, though.",
        str_onbreak = "Whaaaa-? Your Corn Earrings shatter on your ears! Shards of jewels get scattered into your ear, causing you to bleed profusely.",
        durability = 2500000,
        style = "beautiful",
        freshness = 10,
    ),
    EwCosmeticItem(
        id_cosmetic = "dogtag",
        str_name = "Dog Tag",
        str_desc = "A plastic Waffle House-branded dog tag. The chain attached is far too short for your neck, so you can only really shimmy it around your wrist.",
        str_onadorn = "You adorn the Dog Tag and get flashbacks to the trenches. If you die with these on, they aren't coming with you to the sewers.",
        durability = 1500,
        style = "tough",
        vendors = ['Waffle House', 'bazaar'],
        price = 2000,
        freshness = 2,
    ),
    EwCosmeticItem(
        id_cosmetic = "cloutgoggles",
        str_name = "Clout Goggles",
        str_desc = "A pair of bulbous ovular sunglasses. They're way too tinted, but hot DAMN do these radiate sick shit energy. They maybe even radiate... cloutlets? You can see the hidden Clout in the world with these on!",
        str_onadorn = "You put on the Clout Goggles and feel... lamer. Other than cloutlets, you can't see anything with these on!",
        str_unadorn = "You take off the Clout Goggles. You lose 10,000 Instagrime followers nigh-instantaneously. The horror!",
        str_onbreak = "Whaaaa-? Your Clout Goggles **SHATTER!** Cloutlets scatter across the floor, splitting from your naked eyes.",
        rarity="Patrician",
        ability = "clout",
        durability = 2500000,
        size = 2,
        style = "cool",
        freshness = 10, # Actually variable, depending on slimeoid's freshness when created ingame. Max of 10.
    ),
    EwCosmeticItem(
        id_cosmetic = "jress",
        str_name = "Jress",
        str_desc = "A dress made out of denim. Smelted by the finest child laborers in Slime Thailand, this denim dress is guaranteed to be out-of-season by next month. Wholesome! It is SOOO trendy, like, omg. You wouldn't BELIEVE! Jeans are so in style, so when they aren't, it's, like, totally tragic. But WHATEVS.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),  
    EwCosmeticItem(
        id_cosmetic = "shorts",
        str_name = "Shorts",
        str_desc = "Simple and breathable. They're comfortable and easy to wear!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "sweatpants",
        str_name = "Sweatpants",
        str_desc = "These comfy pants are usually used for napping or exercise, but they work perfectly fine for anything else.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "hoodie",
        str_name = "Hoodie",
        str_desc = "Simple, has pockets, and can be worn over a shirt. How can it go wrong?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 4,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "visorcap",
        str_name = "Visor Cap",
        str_desc = "A semi-transparent visor you fit onto your head to protect yourself from harsh overhead lighting. Great against the sun and the harsh reality of being outside!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 4,
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "longsleeveshirt",
        str_name = "Long-Sleve Shirt",
        str_desc = "A generic long-sleeved shirt, lovingly crafted by the owner of the bodega. Its long sleeves cover the entirety of your arms, making them durable against the cold! In addition, its finely-tailored fit makes it look perfect on your sweet bod.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 2,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "suspenders",
        str_name = "Suspenders",
        str_desc = "Popularized by the scramblebrained egghead professors over at NLACakaNM UNI, these things are near-guaranteed to make you nerdier, and a target amongst your fellow gang members.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "japaneseschooluniform",
        str_name = "Japanese School Uniform",
        str_desc = "It's a japanese highschool uniform. Not exactly what you'd call the height of fashion. Why do they make you wear uniforms, haven't they ever heard of individuality?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 2,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "punkvest",
        str_name = "Punk Vest",
        str_desc = "A sick denim jacket with real metal spikes! The vest is covered in many patches and pins from either local NLACakaNM bands or anti-SlimeCorp propaganda. You try to touch said spikes and end up pricking your finger!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "rabbitheadband",
        str_name = "Rabbit Ear Headband",
        str_desc = "These long fake ears blow about in the slightest gust of air, PLUS they often hit the top of any doorframe you enter into. How annoying!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        ability = "furry",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "dogheadband",
        str_name = "Dog Ear Headband",
        str_desc = "The floppy dog ears look straight out of a cartoon, often slapping around whenever you shake your head fast enough. Woof woof!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        ability = "furry",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "catheadband",
        str_name = "Cat Ear Headband",
        str_desc = "These imitation ears can give the illusion of being a cat person from one of your japanese animes. Oh the anatomically incorrect horror!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        ability = "furry",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "demonheadband",
        str_name = "Demon Horn Headband",
        str_desc = "These imitation horns make you look absolutely devilish, ready to cause mischief and misdeeds. Muahahaha!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        ability = "demon",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bugheadband",
        str_name = "Bug Antenna Headband",
        str_desc = "The fake antenna on these bounce around at any slight motion, often smacking yourself in the face. Buzzzzz!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        ability = "bug",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "wolfheadband",
        str_name = "Wolf Ear Headband",
        str_desc = "These fake ears are bound to strike fear into the hearts of prey and hunters alike. Awoooooooo!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        ability = "furry",
        freshness = 6,
        price = 500000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "comictee",
        str_name = "Comic Book Graphic Tee",
        str_desc = "A t-shirt adorning your favorite comic superhero or villian. Just because you only read Omegaverse fanfictions doesn't make you a poser!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 5,
        price = 100000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cartoontee",
        str_name = "Cartoon Graphic Tee",
        str_desc = "A t-shirt plastered with your favorite bizney or cartoon character. You're 90 percent sure the art was stolen straight from a DeviantSplaart you favorited...",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 5,
        price = 100000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "2000sbootyshorts",
        str_name = "2000s Booty Shorts",
        str_desc = "I'm sure that whoever wears these only does it because they like the patterns they come in. Yep, mhm. Not because of any other reason.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 4,
        price = 300000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "gamertee",
        str_name = "Gamer Graphic Tee ",
        str_desc = "A t-shirt referencing your favorite retro game. Irrefutably, this makes you a **TRUE GAMER**. Gootube Channel and stupid smile not included.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 5,
        price = 100000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "devilmanshirt",
        str_name = "Devilman Shirt ",
        str_desc = "I'm Devilman!!! No, not really. I just bought this cheap shirt to cosplay...",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 5,
        price = 100000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "tacohat",
        str_name = "Taco Bell Loyalty Hat",
        str_desc = "A hat with 'Taco Bell Tycoon!' printed on it. Wearing it really makes you want to purchase an Oven-Ready Quesarito with Freshly-Fried Nacho Fries and a Tang-tastic Baja Blast.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 2,
        price = 25000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pizzahat",
        str_name = "Pizza Hut Loyalty Hat",
        str_desc = "A hat with 'Pizza Hut Appreciator!' printed on it. Wearing it really makes you want to purchase an Original Double Stuffed Crust Pizza, with a Scrumptious Whack Calzone for the side.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 2,
        price = 25000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "kfchat",
        str_name = "KFC Loyalty Hat",
        str_desc = "A hat with 'KFC Kraver!' printed on it. Wearing it really makes you want to purchase a Delicious Bucket of Fried Chicken, made with the Elusive Eleven Herbs and Spices.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 2,
        price = 25000,
        vendors = ['Snot Topic'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "leatherpants",
        str_name = "Leather Pants",
        str_desc = "This pair of leather pants is honestly two sizes beneath your waist size, and these stores never have your fucking size. I guess you'll have to live with it.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 5,
        price = 100000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "animetee",
        str_name = "Anime Graphic Tee",
        str_desc = "A t-shirt coated in your trash waifu/husbando of choice, scantily clad of course. Onlookers just fear the sight of you when you pass by.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 5,
        price = 50000,
        vendors = ['Snot Topic'],
    ),
    EwCosmeticItem(
        id_cosmetic = "platformboots",
        str_name = "Platform Boots",
        str_desc = "A glossy pair of knee-length leather platform boots, with multiple buckles strewn about. The goth energy they radiate makes you *feel* more powerful as a juvenile. Crush your enemies beneath your foot!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 7,
        price = 600000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "deviouskicks",
        str_name = "Devious Kicks",
        str_desc = "With pointed ends, these shoes are a staple for beginner villains.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 5,
        price = 300000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "sneakers",
        str_name = "Sneakers",
        str_desc = "A pair of shoes that look as fresh as they did when you popped them out of the box. Or, err, maybe found lying on a street corner. They smell oddly clean? Either way, if you enjoy the rush of running, then you're just in luck.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 5,
        price = 300000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "toeshoes",
        str_name = "Toe Shoes",
        str_desc = "You can wiggle your little piggies while telling the whole world you take hiking to the EXTREME like the asshole you are.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 5,
        price = 300000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "spurs",
        str_name = "Spurs",
        str_desc = "They jingle jangle jingle! These spurs are made to attach to any shoe you want.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 2,
        price = 400000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "geta",
        str_name = "Geta",
        str_desc = "With the growing group of the 'Red Ronins' some fashion brands have started to ask a woodworking company out in Japan to send NLACakaNM these sandals. Worn by many of those that wish to get that samurai look going.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        price = 600000,
        vendors = ['Caravan'],
    ),
    EwCosmeticItem(
        id_cosmetic = "bikini",
        str_name = "Bikini",
        str_desc = "It's one of those... things, one of those gross things that has no usability here in NLACakaNM. Everybody and their slimeoids know not to try swimming into the Slime Sea, and there isn't any fucking water parks here. Where did these come from? Why did some asshole entrepeneur try to sell these seditious pieces of fabric?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 9,
        price = 1000000,
        vendors = ['beachresort'],
    ),
    EwCosmeticItem(
        id_cosmetic = "trenchcoat",
        str_name = "Trench Coat",
        str_desc = "A classic among people who want to show off dubious or otherwise edgy intentions. The pictures you take while wearing this will age horribly the older you get, unless you start wearing it at the ripe age of 40 and above. Above that point it's an old man coat and suitable for wearing.",
        rarity = "Patrician",
        durability = 2500000,
        style = "evil",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "rippedjeans",
        str_name = "Ripped Jeans",
        str_desc = "Many people keep asking how to get ripped jeans, but you know the answer. Oh, and how you'll misinform everyone else.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "flagcape",
        str_name = "Flag Cape",
        str_desc = "Turn your flag into an fucking SICK cape! (Be warned, it's still flammable!)",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 7,
        price = 3000000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "shortshorts",
        str_name = "Short Shorts",
        str_desc = "Shorts, but shorter. Brings you more attention from fiendish folk.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "shortshortshorts",
        str_name = "Short Short Shorts",
        str_desc = "This barely even passes as clothing anymore.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 10,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "tomatotinsuit",
        str_name = "Tomato Tin Suit",
        str_desc = "It's a giant fucking tomato soup tin can, you pescetarian.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 4,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "heavymetalarmor",
        str_name = "Heavy Metal Armor",
        str_desc = "Armor so heavy... you can barely wear it, let alone walk.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "evil",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonebevor",
        str_name = "Monster Bone Bevor",
        str_desc = "It's a piece of monster bone armor that was handmade. This piece will keep your nose and neck nice and guarded.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 2,
        acquisition = "smelting",
        price = 50000,
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonegauntlets",
        str_name = "Monster Bone Gauntlets",
        str_desc = "It's a piece of monster bone armor that was handmade. This piece will keep your arms and hands nice and guarded.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonefullplate",
        str_name = "Monster Bone Fullplate",
        str_desc = "It's a piece of monster bone armor that was handmade. This piece will keep your chest and vitals nice and guarded.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 4,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonegreaves",
        str_name = "Monster Bone Greaves",
        str_desc = "It's a piece of monster bone armor that was handmade. This piece will keep your waist and legs nice and guarded.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 2,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonesabatons",
        str_name = "Monster Bone Sabatons",
        str_desc = "It's a piece of monster bone armor that was handmade. This piece will keep your feet nice and guarded.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 2,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonearmor",
        str_name = "Monster Bone Armor",
        str_desc = "Through all of your hunting, you've finally made the whole set and joined it together. Now you can enjoy the looks on raiders' faces as they watch you stomp your way through the outskirts, knowing that it's just not worth the risk of their lives to engage you. Of course, you're going to kill them all anyways.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 15,
        acquisition = "smelting",
        price = 50000,
        size = 2,
    ),
    EwCosmeticItem(
        id_cosmetic = "monsterbonecodpiece",
        str_name = "Monster Bone Cod piece",
        str_desc = "Because a full set wasn't enough.",
        rarity = "Profollean",
        durability = 2500000,
        style = "evil",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "diamondhelmet",
        str_name = "Diamond Helmet",
        str_desc = "Ill-fitting. Desirable. A symbol of an illustrious gangster. This may as well be your gamer crown, as a blocky helmet made of pure diamonds forged in the sheer wastefulness of the slime poudrins now rests upon your head. Goons look at you and they weep tears of joy, everyone else weeping in laughter from how much of a time-waster this must have been.",
        rarity = "Profollean",
        durability = 36300000,
        style = "beautiful",
        freshness = 15,
        acquisition = "smelting",
        price = 500000000,
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "diamondchestplate",
        str_name = "Diamond Chestplate",
        str_desc = "Ill-fitting. Desirable. A symbol of an illustrious gangster. This solid husk of beauty is now the centerpiece of your personality. You flex, and the diamonds show more than your muscles ever will.",
        rarity = "Profollean",
        durability = 52800000,
        style = "beautiful",
        freshness = 15,
        acquisition = "smelting",
        price = 800000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "diamondleggings",
        str_name = "Diamond Leggings",
        str_desc = "Ill-fitting. Desirable. A symbol of an illustrious gangster. These pants are all the slosh appeal you will ever goddamn need. You're never going to slosh though, you're a goon.",
        rarity = "Profollean",
        durability = 49500000,
        style = "beautiful",
        freshness = 15,
        acquisition = "smelting",
        price = 600000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "diamondboots",
        str_name = "Diamond Boots",
        str_desc = "Ill-fitting. Desirable. A symbol of an illustrious gangster. All the citizens of NLACakaNM *wish* they could be showing off these boots on instagrime. You'll never part with these, even if you'll have to adjust the shoe size every six months.",
        rarity = "Profollean",
        durability = 42900000,
        style = "beautiful",
        freshness = 15,
        acquisition = "smelting",
        price = 400000000,
    ),
    #EwCosmeticItem(
    #    id_cosmetic = "fanhoodie",
    #    str_name = "Fan Hoodie",
    #    str_desc = "You haven't even personalized anyone into this hoodie, and that makes you an awful person.",
    #    rarity = "Plebeian",
    #    durability = 2500000,
    #    style = "evil",
    #   freshness = 0,
    #    price = 50000,
    #    vendors = ['Snot Topic'],
    #), Soon. I'll need to talk about this subject more with other people on the right way of implementing this. 
    EwCosmeticItem(
        id_cosmetic = "jeans",
        str_name = "Jeans",
        str_desc = "A set of jeans that look like they've been in a box in someone's attic for at least a century. Finally! COMMUNIST BASTARDS! I'm shitting my dick right now!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 3,
        price = 50000,
        vendors = ['Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "yarmulke",
        str_name = "Yarmulke",
        str_desc = "Oy Vey!", # For the love of all that is holy please do not smite me down, Igonis was the one behind this item.
        rarity = "Patrician",
        durability = 2500000,
        style = "smart",
        freshness = 5,
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "flatcap",
        str_name = "Flat Cap",
        str_desc = "Popularized by jaded middle-aged men ignoring their household wives, these flat caps are must-have headwear for golfing.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 5,
        price = 1000000,
        vendors = ['Country Club'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "collaredshirt",
        str_name = "Collared Shirt",
        str_desc = "Worn by obedient yuppies and the general middle-class, collarized shirts are the dullest thing ever for someone like a gangster. But what if you want to look like *that* Gootuber?",
        rarity = "plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 8,
        price = 2500000,
        vendors = ['Country Club'],
    ),
    EwCosmeticItem(
        id_cosmetic = "golfshorts",
        str_name = "Golf Shorts",
        str_desc = "You have no idea what separates these from the usual shorts. Is it the pattern? The material? You'll probably never know; it could just be overpriced bullshit.",
        rarity = "Patrician",
        durability = 2500000,
        style = "smart",
        freshness = 7,
        price = 3000000,
        vendors = ['Country Club'],
    ),
    EwCosmeticItem(
        id_cosmetic = "golfoxfords",
        str_name = "Golf Oxfords",
        str_desc = "These atypical sport shoes are used only in golfing - something about needing grip strength for your golf swing. Who the fuck would justify the price tag just for this?",
        rarity = "Patrician",
        durability = 2500000,
        style = "smart",
        freshness = 10,
        price = 5000000,
        vendors = ['Country Club'],
    ),
    EwCosmeticItem(
        id_cosmetic = "snorkelmask",
        str_name = "Snorkel Mask",
        str_desc = "Prepared to go on a diving trip into the Slime Sea? Of course you are, you fucking idiot. Have fun !jumping into the waters!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 2,
        price = 50000,
        vendors = ['Beach Resort'],
    ),
    EwCosmeticItem(
        id_cosmetic = "beachtowel",
        str_name = "Beach Towel",
        str_desc = "Perfect for drying off, this oversized beach towel wraps around your body at least several times. You nearly trip over yourself as soon as you walk forward.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        price = 500000,
        vendors = ['Beach Resort'],
    ),
    EwCosmeticItem(
        id_cosmetic = "poolnoodle",
        str_name = "Pool Noodle",
        str_desc = "Made from super-buoyant material, you can wrap one around your neck like some sort of uncomfortable scarf, or cut down the middle and clamp it on your shoulders, or many other things! But we all know you're going to wield it like a club and whack people with it uselessly. Anyways...",
        rarity = "Patrician",
        durability = 2500000,
        style = "tough",
        freshness = 7,
        price = 1000000,
        vendors = ['Beach Resort'],
    ),
  EwCosmeticItem(
        id_cosmetic = "vape",
        str_name = "Vape",
        str_desc = "A sick-ass vape. SUPER in nowadays. Takes disposable vape pods as its medium of juice.",
        str_onadorn = "You flick the vape into your pocket, ready to whip out at a moment's notice. Gotta keep non-vapers on their toes.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        price = 30000,
        vendors = ['bazaar', 'Slimy Persuits'],
    ),
    EwCosmeticItem( # Make available later in the future somehow, change from promotional to plebeian.
        id_cosmetic = "nmsmascothead",
        str_name = "NMS Mascot Head",
        str_desc = "A mascot head, fashioned to look like the front of an airplane. It's got a little twirly bit at the top.",
        str_onadorn = "You put on the mascot head. **Ptch-ooooooo!!!!**",
        str_unadorn = "You take off the mascot head. **BHHOOOOMMMM!!!!**",
        rarity = "Promotional",
        ability = "nmsmascot",
        durability = 2500000,
        style = "smart",
        freshness = 3,
        price = 200,
        vendors = [''],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "nmsmascottorso",
        str_name = "NMS Mascot Torso",
        str_desc = "A mascot torso, fashioned to look like the fuselage of an airplane. There's a boob window showing a pair of airplane breasts, though.",
        str_onadorn = "You put on the mascot torso. **Fwhheeeeeee!!!!**",
        str_unadorn = "You take off the mascot torso. **BHHOOOOMMMM!!!!**",
        rarity = "Promotional",
        ability = "nmsmascot",
        durability = 2500000,
        style = "cute",
        freshness = 3,
        price = 400,
        vendors = [''],
    ),
    EwCosmeticItem(
        id_cosmetic = "nmsmascotlegs",
        str_name = "NMS Mascot Legs",
        str_desc = "A pair of mascot legs, fashioned to look like the tail of an airplane. The resemblance is uncanny.",
        str_onadorn = "You put on the mascot legs. **Fhhhfhhhfhhhfhhhfhhh!!!!**",
        str_unadorn = "You take off the mascot legs. **BHHOOOOMMMM!!!!**",
        rarity = "Promotional",
        ability = "nmsmascot",
        durability = 2500000,
        style = "tough",
        freshness = 3,
        price = 300,
        vendors = [''],
    ),
    EwCosmeticItem(
        id_cosmetic = "nmsmascotwings",
        str_name = "NMS Mascot Wings",
        str_desc = "A pair of mascot wings, fashioned to look an airplane's. They're incredibly heavy, sure to give you back problems.",
        str_onadorn = "You put on the mascot wings. **Whhhhhhhhhhhhiiiiiiirrrrrrrrrrrrr!!!**",
        str_unadorn = "You take off the mascot wings. **BHHOOOOMMMM!!!!**",
        rarity = "Promotional",
        ability = "nmsmascot",
        durability = 2500000,
        style = "cool",
        freshness = 3,
        price = 500,
        vendors = [''],
    ),
    EwCosmeticItem(
        id_cosmetic = "nmsmascotwheels",
        str_name = "NMS Mascot Wheels",
        str_desc = "A pair of mascot wheels, designed to clip on to your shoes. They make walking a complete *plane*.",
        str_onadorn = "You put on the mascot wheels. **Rrhrhrhrhrhrhrhrhrh!!!!**",
        str_unadorn = "You take off the mascot wheels. **BHHOOOOMMMM!!!!**",
        rarity = "Promotional",
        ability = "nmsmascot",
        durability = 2500000,
        style = "beautiful",
        freshness = 3,
        price = 250,
        vendors = [''],
    ),
    EwCosmeticItem(
        id_cosmetic = "amateurichthyologistpin",
        str_name = "Amateur Ichthyologist Pin",
        str_desc = "A pin given to you by the Curator for a grand contribution to ichthyologykind you've made. The paint is chipping.",
        str_onadorn = "You stick the tiny amateur icthyologist pin on.",
        str_unadorn = "You take the tiny amateur ichthyologist pin off.",
        rarity = "Promotional",
        durability = 35000,
        style = "smart",
        freshness = 3,
    ),
    EwCosmeticItem(
        id_cosmetic = "amateurarcheologistpin",
        str_name = "Amateur Archeologist Pin",
        str_desc = "A pin given to you by the Curator for a grand contribution to archeologykind you've made. It's somehow misspelled \"archiologist\".",
        str_onadorn = "You stick the tiny amateur archeologist pin on.",
        str_unadorn = "You take the tiny amateur archeologist pin off.",
        rarity = "Promotional",
        durability = 35000,
        style = "smart",
        freshness = 3,
    ),
    EwCosmeticItem(
        id_cosmetic = "amateurartistpin",
        str_name = "Amateur Artist Pin",
        str_desc = "A pin given to you by the Curator for your a great work of artistry you've made. Good for you, I guess.",
        str_onadorn = "You stick the tiny amateur archeologist pin on.",
        str_unadorn = "You take the tiny amateur archeologist pin off.",
        rarity = "Promotional",
        durability = 35000,
        style = "smart",
        freshness = 3,
    ),
    EwCosmeticItem(
        id_cosmetic = "programmersocks",
        str_name = "Programmer Socks",
        str_desc = "Long stripey socks that programmers wear when they inevitably come out as trans. Oddly rare around here...",
        str_onadorn = "You slip on the programmer socks. This better not be Stotle using these...",
        str_unadorn = "You take off the programmer socks. Please, do us all a favor and do not post pics of your feet.",
        str_onbreak = "FREEDOM! The socks rip apart!",
        durability = 2500000,
        freshness = 10,
    ),
    EwCosmeticItem(
		id_cosmetic = "maidoutfit",
        str_name = "Maid outfit",
        str_desc = "A cute little maid outfit! You look so cute with the little skirt and the little head thing that you don't remember the name of... You would rather not remember the things you had to do to get this outfit.",
        str_onadorn = "You pull on the maid outfit, ready to get to work!",
        str_unadorn = "You quickly pull off the outfit. \"Mom, I can explain!\" You shout as she runs away in shame.",
        durability = 2500000,
        style = "cute",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "cigaretteholder",
        str_name = "Cigarette Holder",
        str_desc = "A long piece of... stick, or something, with a cigarette spot on the end. You are too unrefined to know the specifics but DANG you look pretty holding it. It could put someone's eye out!",
        str_onadorn = "You stick the cigarette holder into your mouth, inhaling deeply before blowing out a puff of smoke.",
        str_unadorn = "You remove the cigarette holder from your mouth and store it in your pocket.",
        durability = 2500000,
        style = "beautiful",
        freshness = 5,
        acquisition = "smelting",
        price = 50000,
    ),
    EwCosmeticItem(
        id_cosmetic = "widebrimmedhat",
        str_name = "Wide Brimmed Hat",
        str_desc = "This hat cost you so many hours, you might as well be the lord of this city! Better not let the patrons see you in it though... They keep asking you to... Crush them...",
        str_onadorn = "You place the wide brimmed hat on your head, the edge flopping over one eye sexily. Oh yeah, lets get this ~~blood~~ bread.",
        str_unadorn = "You remove the wide brimmed hat, setting it down. You feel shorter now.",
        durability = 2500000,
        style = "beautiful",
        freshness = 8,
        acquisition = "smelting",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "drapeddress",
        str_name = "Draped Evening Dress",
        str_desc = "A long gown, with ample room for large bosoms and tall stature. It is fitted for someone of height 289.56 cm. If you are shorter than that, it's gonna be pooling around your feet."
        str_onadorn = "You slide into the beautiful dress... you are now absolutely breathtaking. Men (and women) bow before you, almost trying to throw themselves under your feet. It is rather annoying.",
        str_unadorn = "Your huge body rips out of the dress, tearing it to shreds! It was no match for your impressive figure! (Don't worry though it still is in your inventory.)",
        durability = 2500000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 5000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "wrappingpapersexywear" # Reasons to never listen to the community, especially M@.
        str_name = "Wrapping Paper Sexywear" # Nobody fucking say anything and let this be a surprise.
        str_desc = "This awful collection of wrapping paper is what you're going to wrap parts of yourself to present yourself as a present. You think this is funny? Even if you wear this during slimernalia, nobody will like you.",
        str_onadorn = "You wrap yourself up in wrapping paper to do the century old reinterpretation of \"I am your present!\"... you do realize that this is gross and wrong, right?", 
        str_unadorn = "You rip off the awful, awful clothing. Of course, this will be your lowest point in your whole life." ,
        durability = 4,
        style = "evil",
        freshness = -1,
        acquisition = "smelting",
        price = 100,
    ),
]


# A map of id_cosmetic to EwCosmeticItem objects.
cosmetic_map = {}

# A list of cosmetic names.
cosmetic_names = []

# A list of grouped cosmetics
cosmetic_nmsmascot = []

# Populate cosmetic map.
for cosmetic in cosmetic_items_list:
    cosmetic_map[cosmetic.id_cosmetic] = cosmetic
    cosmetic_names.append(cosmetic.id_cosmetic)
    if cosmetic.ability == "nmsmascot":
        cosmetic_nmsmascot.append(cosmetic.id_cosmetic)
