import json
import os

from ..model.item import EwCosmeticItem

cosmetic_items_list = [
    EwCosmeticItem(
        id_cosmetic = "propellerhat",
        str_name = "propeller hat",
        str_desc = "A simple multi-color striped hat with a propeller on top. A staple of every juvenile�s youth.",
        str_onbreak = "Your hat takes a hit, detatching the propeller and sending it twirling into the stratosphere. Looks like you'll never see it again.",
        rarity = "Plebeian",
        durability = 2500000,
        size = 1,
        style = "cute",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "mininghelmet",
        str_name = "mining helmet",
        str_desc = "A typical construction hard hat with a head lamp strapped onto it.",
        rarity = "Plebeian",
        ability = "lucky",
        durability = 5000000,
        size = 2,
        style = "tough",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pickelhaube",
        str_name = "pickelhaube",
        str_desc = "A traditional Prussian spiked helmet from the nineteenth century.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "fedora",
        str_name = "fedora",
        str_desc = "A soft brimmed hat with a pinched crown. A classic piece of vintage Americana and a staple of film noir. Not to be confused with the trilby, the fedora is a hat befitting the hardboiled men of its time.",
        rarity = "Plebeian",
        durability = 1250000.0,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "baseballcap",
        str_name = "baseball cap",
        str_desc = "A classic baseball cap. A staple of American culture and subsequently freedom from tyranny. If you don�t own at least one of these hats you might as well have hopped the fence from Tijuana last night. Yeah, I�m racist, that going to be a problem for you??",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "backwardsbaseballcap",
        str_name = "backwards baseball cap",
        str_desc = "A classic baseball cap� with an urban twist! Heh, 'sup dawg? Nothing much, man. You know me, just mining some goddamn slime. Word 'n shit. Hell yeah.",
        str_onadorn = "You whip out your baseball cap and apply it...backwards. Fuck, now we're getting serious.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "piratehat",
        str_name = "pirate hat",
        str_desc = "A swashbuckling buccaneer�s tricorne, stylized with a jolly roger on the front.",
        str_onadorn = "Y'ARRRRRRR! You adorn ye' tricorne and spit at a nearby pedestrian.",
        str_onbreak = "You hat is torn to shreds. Welp, no more shivering timbers.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "eyepatch",
        str_name = "eyepatch",
        str_desc = "A black eyepatch. A striking accessory for the particularly swashbuckling, chauvinistic, or generally hardboiled of you. Genuine lack of two eyes optional and not recommended.",
        str_unadorn = "You remove your eyepatch to reveal the grisly wound benea- wait. Your eye is just fine! What kind of pathetic pirate LARPer did you turn out to be?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cigarette",
        str_name = "cigarette",
        str_desc = "A single cigarette sticking out of your mouth. You huff these things down in seconds but you�re never seen without one. Everyone thinks you�re really, really cool.",
        str_onadorn = "You stick the cigarette in your mouth, suave as a baby's bottom. You wonder how many of these could fit in your mouth.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "headband",
        str_name = "headband",
        str_desc = "A headband wrapped tightly around your forehead with long, flowing ends.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "handkerchief",
        str_name = "handkerchief",
        str_desc = "A bandanna tied on your head, creating a simple cap.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "bandanna",
        str_name = "bandanna",
        str_desc = "A handkerchief tied around your neck and covering your lower face.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofsunglasses",
        str_name = "pair of sunglasses",
        str_desc = "An iconic pair of black sunglasses. Widely recognized as the coolest thing you can wear.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofglasses",
        str_name = "pair of glasses",
        str_desc = "A simple pair of eyeglasses. You have perfectly serviceable eyesight, but you are a sucker for the bookworm aesthetic. People with actual issues with sight hate you.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "birthdayhat",
        str_name = "birthday hat",
        str_desc = "A striped, multi-color birthday hat. ",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "scarf",
        str_name = "scarf",
        str_desc = "A very thick striped wool scarf, in case 110� degrees is too nippy for you.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "witchhat",
        str_name = "witch hat",
        str_desc = "A pointy, cone-shaped hat with a wide brim. It exudes a spooky essence.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bomberhat",
        str_name = "bomber hat",
        str_desc = "A thick fur and leather aviator�s hat.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "tuxedo",
        str_name = "tuxedo",
        str_desc = "A classy, semi-formal suit for dashing rogues you can�t help but love. Instant charisma granted upon each !adorn.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "beanie",
        str_name = "beanie",
        str_desc = "A simple beanie with a pointed top and a slip stitch brim.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "jestershat",
        str_name = "jester's hat",
        str_desc = "A ridiculous, multi-colored hat with four bells dangling from protruding sleeves.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairof3dglasses",
        str_name = "pair of 3D glasses",
        str_desc = "A pair of totally tubular, ridiculously radical 3D glasses. Straight up stereoscopic, dude!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "necktie",
        str_name = "necktie",
        str_desc = "A vintage necktie, reeking of coffee, college, and shaving cream.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "vikinghelmet",
        str_name = "viking helmet",
        str_desc = "A pointy bronze helmet with two sharp horns jutting out of the base.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofflipflops",
        str_name = "pair of flip flops",
        str_desc = "A pair of loud, obnoxious flip flops. The price of your comfort is higher than you could ever know.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 3,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "fez",
        str_name = "fez",
        str_desc = "A short fez with a tassel attached to the top. Fezzes are cool. Or, are bowties cool? You forget, and frankly you�re embarrassed you remember either one of them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bowtie",
        str_name = "bowtie",
        str_desc = "A quite dapper, neatly tied butterfly bowtie. Bowties are cool. Or, are fezzes cool? You forget, and frankly you�re embarrassed you remember either one of them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cowboyhat",
        str_name = "cowboy hat",
        str_desc = "An essential piece of Wild West memorabilia, a bonafide ten gallon Stetson. Befitting the individualistic individuals that made them famous. Yeehaw, and all that stuff.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "kepi",
        str_name = "kepi",
        str_desc = "A short kepi with a sunken top and an insignia on the front.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "tamoshanter",
        str_name = "tam o' shanter",
        str_desc = "A traditional Scottish wool bonnet with a plaid pattern.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "ushanka",
        str_name = "ushanka",
        str_desc = "A traditional Russian fur cap with thick wool ear flaps.",
        rarity = "Plebeian",
        durability = 5000000,
        size = 2,
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "karategi",
        str_name = "karategi",
        str_desc = "A traditional Japanese karateka�s outfiit, complete with a belt with extended ends that easily flow in the wind for dramatic effect.",
        rarity = "Plebeian",
        style = "tough",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "turban",
        str_name = "turban",
        str_desc = "A traditional Arabian headdress, lavishly decorated with a single large jewel and protruding peacock feather.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "nemes",
        str_name = "nemes",
        str_desc = "The traditional ancient Egyptian pharaoh's striped head cloth.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "varsityjacket",
        str_name = "varsity jacket",
        str_desc = "An American baseball jacket, with a large insignia on the left side of the chest.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 9,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "sombrero",
        str_name = "sombrero",
        str_desc = "A traditional Mexican sombrero, with an extra-wide brim to protect you from the blistering Arizonian sun.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "hawaiianshirt",
        str_name = "hawaiian shirt",
        str_desc = "A brightly colored Hawaiian shirt with a floral pattern. It reeks of slima colada and the complementary shampoo from the resort in Assault Flats Beach.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "fursuit",
        str_name = "fursuit",
        str_desc = "A fursuit. Custom-made and complete with high quality faux fur, padded digitigrade legs, follow-me eyes, adjustable facial expressions, and a fan in the head. It is modeled off your original character, also known as your fursona. Some would call its character design �ugly� or �embarrassing,� but you think it's perfect.",
        rarity = "Patrician",
        durability = 10000000,
        size = 2,
        style = "cute",
        freshness = 11,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "diadem",
        str_name = "diadem",
        str_desc = "The traditional Greco-Roman laurel wreath symbolizing sovereignty and power. Be careful about wearing this around in public, you might just wake up with 23 stab wounds.",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "billshat",
        str_name = "Bill's Hat",
        str_desc = "A military beret with a shield insignia on the front.",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 9,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "weddingring",
        str_name = "wedding ring",
        str_desc = "A silver ring with a decently large diamond on top. For the person you love most in the entire world. <3",
        rarity = "Patrician",
        durability = 10000000,
        style = "beautiful",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "earbuds",
        str_name = "earbuds",
        str_desc = "A pair of white standard iPod earbuds. Who knows what sort of tasty jams you must be listening to while walking down the street?",
        rarity = "Patrician",
        durability = 10000000,
        style = "smart",
        freshness = 10,
        acquisition = "smelting",
        price = 1000000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "nursesoutfit",
        str_name = "nurse's outfit",
        str_desc = "A disturbingly revealing nurse�s outfit that shows off your lumpy, fleshy visage. No one likes that you wear this. Theming bonus for responding to people�s crackpot ideas in the nurse�s office, though.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 6,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "heartboxers",
        str_name = "heart boxers",
        str_desc = "A staple of comedy. A pair of white boxers with stylized cartoon hearts tiled all over it. Sure hope your pants aren�t hilariously ripped or unadorned while you�re wearing these, how embarrassing! Hahaha! We like to have fun here.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "kilt",
        str_name = "Kilt",
        str_desc = "A traditional scottish garmet that's plaid, and it's not a fuckin' skirt, aight?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "cigar",
        str_name = "Cigar",
        str_desc = "Much more manly then a puny cigarette. This cigar has been freshly imported from cuba and is thick enough to last for hours.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "captainshat",
        str_name = "Captain's Hat",
        str_desc = "The perfect hat for sailing across the Slime Sea, commanding a navy fleet, or prematurely ending your lucrative My Little Pony review series in favor of starting a shitty Pokemon Nuzlocke series. For shame.",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "juveolantern",
        str_name = "Juve-O'-Lantern",
        str_desc = "Hand-carved with a hole just barely big enough to fit your head in, this Juve O' Lantern severely hinders your combat ability. But, you look fucking sick while wearing it, so who cares.",
        durability = 2500000,
        style = "cute",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bowlerhat",
        str_name = "Bowler Hat",
        str_desc = "A simply traditional billyock. You�re gonna be the talk of the toy box with this dashing felt cosmetic! Now you just have to work on the moustache.",
        durability = 2500000,
        style = "smart",
        freshness = 6,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "cabbagetreehat",
        str_name = "Cabbage Tree Hat",
        str_desc = "An unmistakably Australian hat, with a wide brim and a high crown.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "braces",
        str_name = "Braces",
        str_desc = "An old fashioned orthodontic headgear. Elaborate metal wires and braces hold your nearly eroded, crooked teeth together in what can genously be called a mouth. You are in agony, and so is everyone that looks at you.",
        durability = 3750000.0,
        style = "smart",
        freshness = 1,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "hoodie",
        str_name = "Hoodie",
        str_desc = "Perfect for keeping warm in the middle of the blisteringly hot Arizonian desert! Heatstroke or bust!",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "copbadge",
        str_name = "Cop Badge",
        str_desc = "What the fuck are you doing with this thing? Are you TRYING to make the sewers your permanent residence? Acquaint yourself with the !drop command and FAST, before you don�t have a body to wear the badge on.",
        durability = 2500000,
        style = "smart",
        freshness = 2,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "strawhat",
        str_name = "Straw Hat",
        str_desc = "A wide-brimmed straw hat, the perfect hat for farming.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "cosplayhorns",
        str_name = "Cosplay Horns",
        str_desc = "You�re not entirely sure what these things are, but they sort of look like brightly painted, candy corn colored, paper mache horns that are hot glued onto a black headband. Their purpose is mysterious, but for some reason you are inclined to adorn them� perhaps you understood their importance in a past life.",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "yourfavoritehat",
        str_name = "***Your Favorite Hat***",
        str_desc = "***It fits perfectly, and it�s just your style! You love wearing this cosmetic far more than any other, it�s simply the best.***",
        durability = 2500000,
        style = "cute",
        freshness = 10,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pajamaonesie",
        str_name = "Pajama Onesie",
        str_desc = "A soft jumpsuit with an audacious, repeating design printed over the entire cosmetic. You feel like getting a little bit fucking rowdy wearing this outrageous onesie. ",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofcircularsunglasses",
        str_name = "Pair of Circular Sunglasses",
        str_desc = "Sunglasses, but in a circle! Genius! You can't wait to show the world your hot takes on television shows for girls.",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "flowercrown",
        str_name = "Flower Crown",
        str_desc = "A lovingly handcrafted crown of flowers, connected by a string. You�re gonna be famous on Pinterest with a look like this!",
        durability = 2500000,
        style = "cute",
        freshness = 7,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "spikedbracelets",
        str_name = "Spiked Bracelets",
        str_desc = "Hilariously unrealistic spiked bracelets, ala Bowser, King of the Koopas. You�re hyper aware of these fashion disasters whenever you�re walking, making sure to swing them as far away from your body as possible.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "slimecorppin",
        str_name = "SlimeCorp Pin",
        str_desc = "An enamel pin of the SlimeCorp logo, a badge of loyalty to your favorite charismatic megacorporation. Dude, like, *�Follow He Who Turns The Wheels�*, bro!!",
        durability = 2500000,
        style = "smart",
        freshness = 10,
        acquisition = "smelting",
        vendors = ['The Breakroom'],
    ),
    EwCosmeticItem(
        id_cosmetic = "overalls",
        str_name = "Overalls",
        str_desc = "Simple, humble denim overalls, for a simple, humble farmer such as yourself.",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "rustynail",
        str_name = "Rusty Nail",
        str_desc = "A large, rusty nail, planted right between the sides of your head, like some kind of frankenstein costume piece. This one's the real deal though... oh god the pain...",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "fullmetaljacket",
        str_name = "Full Metal Jacket",
        str_desc = "A black leather jacket affixed with more spikes than you can count on your fingers and toes. Be careful not to bump into anyone with this thing on.",
        durability = 5000000,
        style = "tough",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "tinfoilhat",
        str_name = "Tinfoil Hat",
        str_desc = "A hat that protects you from SlimeCorp's patent-pending 5G binaural brain waves, or so the folks on the internet have told you.",
        durability = 5000000,
        style = "smart",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "resplendentcoronet",
        str_name = "Resplendent Coronet",
        str_desc = "A crown worn by only the most elegant and regal of nobles. When you put it on, you really feel like you fuckin' own the place.",
        durability = 5000000,
        style = "beautiful",
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "raincoat",
        str_name = "Raincoat",
        str_desc = "A specially engineered piece of personal armor, that protects you from the deadly threat from above.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        price = 50000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "halloweenmedallion",
        str_name = "Double Halloween Medallion",
        str_desc = "A glistening crystal medallion, carved in the shape of a pumpkin. It is strewn together with black pearls. Awarded only to the bravest of souls who managed to best the Double Headless Double Horseman in combat.",
        rarity = "Double Halloween",
        style = "cool",
        ingredients = "HorsemanSoul",
        acquisition = "DH-bossfight",
    ),
    EwCosmeticItem(
        id_cosmetic = "pileus",
        str_name = "Pileus",
        str_desc = "A symbol of freedom and liberty. In ancient times, these felt caps were given to slaves who had been emancipated.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        price = 100,
    ),
    EwCosmeticItem(
        id_cosmetic = "seacowcostume",
        str_name = "Attractive Gray Sea Cow Mascot Costume for Adult",
        str_desc = "Attractive. That's really all there is to say on the matter.",
        rarity = "Patrician",
        durability = 2500000,
        style = "beautiful",
        freshness = 2,
        price = 100000000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "wrappingpaperhat",
        str_name = "Wrapping Paper Hat",
        str_desc = "A hat made out of wrapping paper, fashioned in a way rather similar to a newspaper hat. How festive!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        price = 1000,
        vendors = ['Glocksbury Comics'],
    ),
    EwCosmeticItem(
        id_cosmetic = "knightarmor",
        str_name = "Steel knight armor",
        str_desc = "A shining set of steel armor.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "velcroshoes",
        str_name = "Velcro Shoes",
        str_desc = "Juveniles in the city always had a hard time tying their laces, so these stylish kicks are perfect for them.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        price = 1000,
        vendors = ['bazaar'],
    ),
    EwCosmeticItem(
        id_cosmetic = "crocs",
        str_name = "Crocs",
        str_desc = "The perfect pair of footwear for when you want spotted dots of sunburn on your feet, unless you're wearing socks that is. If that's the case ignore that earlier statement.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 6,
        price = 1000,
        vendors = ['bazaar', 'Secret Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "janusmask",
        str_name = "Janus Mask",
        str_desc = "A simple, yet elegant mask, awarded to those deemed worthy by Janus himself at the end of every Swilldermuk. It's enigmatic powers allow you to procure prank items from thin air.",
        rarity = "Swilldermuk",
        durability = 10000000,
        style = "cool",
        ingredients = "SwilldermukFinalGambit",
        acquisition = "SwilldermukEnd",
    ),
    EwCosmeticItem(
        id_cosmetic = "leatherjacket",
        str_name = "Leather Jacket",
        str_desc = "A black leather jacket. Gangs of Killers stalking the streets are often found wearing these.",
        rarity = "Patrician",
        durability = 2500000,
        style = "cool",
        price = 50000,
        vendors = ['bazaar', 'Bodega'],
    ),
    EwCosmeticItem(
        id_cosmetic = "afrowig",
        str_name = "Afro Wig",
        str_desc = "The perfect hair-do for a 70's party or a pool party just be sure to keep a can of hairspray and comb at hand.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pompadourwig",
        str_name = "Pompadour Wig",
        str_desc = "A must have for any wannabe greaser or school delinquent in general. Make sure to wear it like a true king.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "powderedwig",
        str_name = "Powdered Wig",
        str_desc = "If it was good enough for the british and founding fathers, it's good enough for us, right? Just make sure you don't share this wig without cleaning it.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "rainbowafrowig",
        str_name = "Rainbow Afro Wig",
        str_desc = "A colorful wig worthy of a real chuckle.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "ghostlygibus",
        str_name = "Ghostly Gibus",
        str_desc = "A crooked old top hat with a spooky toy ghost popping out of the top.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "gasmask",
        str_name = "Gas Mask",
        str_desc = "A dysfunctional cold war era gas mask that fully encapsulates the head.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "firefightershelmet",
        str_name = "Firefighter's Helmet",
        str_desc = "A old NLACakaNM wide-brimmed red firefighter's helmet. No one knows what happened to the firefighters of Endless War.",
        rarity = "Plebeian",
        durability = 3750000.0,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "pairofpoindexterglasses",
        str_name = "Pair Of Poindexter Glasses",
        str_desc = "A pair of thick rim glasses taped together at the middle. Worthy of any true nerd or nerdette.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "duncecap",
        str_name = "Dunce Cap",
        str_desc = "It�s a pointy cap that says dunce on it, duh! You�re a real smartie aren't you?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cute",
        freshness = 2,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "vrheadset",
        str_name = "VR Headset",
        str_desc = "Endless War -- now in stunning VR!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        freshness = 8,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "blindfold",
        str_name = "Blindfold",
        str_desc = "Ok now you�re just bragging. Walking around with a blindfold of all things? How ridiculous!",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "chickenmask",
        str_name = "Chicken Mask",
        str_desc = "The rubber chicken mask gives you a strange vibe. It stinks of sweat and dried blood.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "mountiehat",
        str_name = "Mountie Hat",
        str_desc = "A hat that's mostly used by Canada's royal mounted police, but how did it get here? Did it float down the slime river?",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "bearskinhat",
        str_name = "Bearskin Hat",
        str_desc = "A towering fuzzy hat that�s commonly worn by guards of the british royal guard.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "smart",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "aviatorshat",
        str_name = "Aviator's Hat",
        str_desc = "A leather hat with a neat pair of goggles on it. Perfect for an unfortunate circumnavigation of the world.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "tough",
        freshness = 6,
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "militaryberet",
        str_name = "Military Beret",
        str_desc = "A good soldier needs good headwear, and that�s where this beret comes in.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "beautiful",
        freshness = 7,
        acquisition = "smelting",
        price = 50000,
        vendors = ['Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "felinehat",
        str_name = "Feline Hat",
        str_desc = "A hat striped with red and white is quite right for a fanciful fight! It�s a funny hat at that, and it looks like it�s been worn by a cat!",
        rarity = "Plebeian",
        durability = 100,
        style = "cute",
        freshness = 1,
        acquisition = "smelting",
        price = 100,
        vendors = ['Secret Bodega'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "tikihead",
        str_name = "Tiki Head",
        str_desc = "A wearable tiki head worthy of any luau or tropical island themed party.",
        rarity = "Plebeian",
        durability = 2500000,
        style = "cool",
        acquisition = "smelting",
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "reinforcedkfcbucket",
        str_name = "Reinforced KFC Bucket",
        str_desc = "A stronger, more durable version of the average KFC bucket. Intended to be worn by shamblers in Dr. Downpour's legion of the undead.",
        rarity = "Patrician",
        durability = 5000000,
        style = "smart",
        price = 1000,
        vendors = ['Downpour Armament Vending Machines'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "reinforcedjuveolantern",
        str_name = "Reinforced Juve-O'-Lantern",
        str_desc = "A stronger, more durable version of the average Juve-O'-Lantern. Intended to be worn by shamblers in Dr. Downpour's legion of the undead.",
        rarity = "Patrician",
        durability = 5000000,
        style = "cute",
        price = 2000,
        vendors = ['Downpour Armament Vending Machines'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "rollerblades",
        str_name = "Rollerblades",
        str_desc = "A wicked sicknasty D-I-Y set of inline skates. These ones may not be magnetically driven or powered by netrium batteries, but they do the job just fine.",
        str_onadorn = "You slip into your rollerblades and tighten the straps. Let's get scratchin'.",
        str_unadorn = "You unfasten the belts and straps on your rollerblades.",
        str_onbreak = "Your rollerblades break down! Time to make a break for it on foot!",
        rarity = "Patrician",
        ability = "boost",
        durability = 250000,
        style = "cool",
        freshness = 10,
        acquisition = "smelting",
    ),
    EwCosmeticItem(
        id_cosmetic = "garfieldtail",
        str_name = "Garfield's Tail",
        str_desc = "The tail of a large ginger cat, \"borrowed\" from it's owner.",
        str_onadorn = "You adorn Garfield's Tail, and feel an overwhelming hatred for Mondays creep into your mind...",
        str_unadorn = "You remove Garfield's Tail. Maybe Mondays aren't so bad after all...",
        str_onbreak = "Whaaaa-? Garfield's Tail disintegrates.",
        rarity = "Safari",
        ability = "mondayblues",
        durability = 250000,
        style = "cute",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "normalplume",
        str_name = "Normal Plume",
        str_desc = "A Normal Plume plucked from N400. Dogs hate this thing.",
        str_onadorn = "You adorn the Normal Plume! Normcoin is too big to fail, I tell you!",
        str_unadorn = "You remove the Normal Plume. Thank god, you almost invested all your savings into a proprietary soul-based cryptocurrency!",
        str_onbreak = "Whaaaa-? The Normal Plume disintegrates.",
        rarity = "Safari",
        ability = "norm",
        durability = 250000,
        style = "beautiful",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "guillotinecharm",
        str_name = "Guillotine Charm",
        str_desc = "A miniature guillotine strung on a piece of rope to go around your neck. What could go wrong?",
        str_onadorn = "You adorn the Guillotine Charm. You feel an intense need to abolish the monarchy.",
        str_unadorn = "You remove the Guillotine Charm. Hmmmm, maybe we SHOULD have a monarchy...",
        str_onbreak = "Whaaaa-? The Guillotine Charm disintegrates.",
        rarity = "Safari",
        ability = "executioner",
        durability = 250000,
        style = "tough",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "ominousslippers",
        str_name = "Ominous Slippers",
        str_desc = "Ominous Slippers fashioned from the paws of an incredibly large dog. One step closer to a full fursuit...",
        str_onadorn = "You adorn the Ominous Slippers. Comfortable, yet something within you wishes to be covered in MORE fur...",
        str_unadorn = "You remove the Ominous Slippers. Phew, you almost *liked* wearing that furry shit for a while there! haha...",
        str_onbreak = "Whaaaa-? The Ominous Slippers disintegrates.",
        rarity = "Safari",
        ability = "moonlighter",
        durability = 250000,
        style = "cute",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "navaluniform",
        str_name = "Naval Uniform",
        str_desc = "One of those old-fashioned Navy uniforms, the bane of children across the globe. It smells faintly of whale...",
        str_onadorn = "You adorn the Naval Uniform. You feel like a kid again! A *naval* kid!",
        str_unadorn = "You remove the Naval Uniform. The responsibilities and pains of adulthood creep back into you. Oh...",
        str_onbreak = "Whaaaa-? The Naval Uniform disintegrates.",
        rarity = "Safari",
        ability = "childatheart",
        durability = 250000,
        style = "smart",
        freshness = 10,
        acquisition = "Safari",
        price = 1000000,
    ),
    EwCosmeticItem(
        id_cosmetic = "raccoonskincap",
        str_name = "Raccoon-skin Cap",
        str_desc = "A cap fashioned from the skin and fur of a raccoon. An iconic hunting cap, and favourite of rats everywhere.",
        str_onadorn = "You slap on the Raccoon-skin cap, the little tail at the back itching your neck.",
        str_unadorn = "You rip the Raccoon-skin cap off of your head at mach speed.",
        str_onbreak = "Whaaaa-? The Raccoon-skin cap runs off into the woods, sick of being a hat.",
        rarity = "Patrician",
        durability = 250000,
        style = "cool",
        freshness = 5,
        price = 50000,
        vendors = ['bazaar'],
        is_hat = True,
    ),
    EwCosmeticItem(
        id_cosmetic = "safaribadge",
        str_name = "Safari Badge",
        str_desc = "A cardboard \"badge\" with \"Safari\" scrawled on it in crayon. It's even got double-sided tape instead of a safety pin! They didn't spare *any* expense!",
        str_onadorn = "You stick the Safari Badge to yourself. You feel a portion of your lost safari power return to you...",
        str_unadorn = "You unstick the Safari Badge from yourself. You feel drained of safari power.",
        str_onbreak = "Whaaaa-? The Safari Badge distintegrates before your very eyes. Thanks for the memories, little friend!",
        rarity = "Safari",
        ability = "safaripower",
        durability = 250000,
        style = "cool",
        freshness = 10,
        price = 50000,
    ),
]


# A map of id_cosmetic to EwCosmeticItem objects.
cosmetic_map = {}

# A list of cosmetic names.
cosmetic_names = []

# Populate cosmetic map.
for cosmetic in cosmetic_items_list:
    cosmetic_map[cosmetic.id_cosmetic] = cosmetic
    cosmetic_names.append(cosmetic.id_cosmetic)
